### ISSUE TITLE
wrong screenshot if we push a tableviewcontroller

### ISSUE THREAD

**Issue by onishinji** [MarcoSero/MSSlideNavigationController#3]
Hi, 

First, thank for your work, it's almost perfect :)

The bug: 
-  add a tableviewcontroller on your storyboard (empty)
-  create un button on viewcontrolerA
- add a triggered segue to the tableviewcontroller to push it.

Now, when we are on tableviewoncoller, go back slowy. The screenshot for the viewControllerA is wrong, it's a black screen (or white in my project). 

If you have an idea to resolve it, you work will became perfect :)

(ps: sorry for my bad english)

**Comment by MarcoSero** [comment]
Thanks for reporting. Duplicate of this https://github.com/MarcoSero/MSSlideNavigationController/issues/2
