### ISSUE TITLE
found some false behaviour when reuse the 'B' controller without initialize again

### ISSUE THREAD

**Issue by kpping** [MarcoSero/MSSlideNavigationController#4]
Here is the step to reproduce the situation that I found on my application:

Assume as I have 2 view controllers, A and B

1.) when I navigate from A to B at the first time, I have init B then push navigation controller to B.

2.) Then slide to go back to A

3.) Go to B again without initialize B (use the same B as (1.) ), now I got some false behaviour with B. It seems like it has a wrapper view (snapshot) at the top of B's view. The view was freezing. I cannot update anything on the screen.

My Solution.
- remove B after coming back to A and re-create B again before push navigation controller to B.

PS. This is my bug and may be It was just because of my code. (but i don't think so)

**Comment by MarcoSero** [comment]
Sorry maybe I didn't get, but when the navigation controller pops a controller, the latter gets deallocated. How can you push it again without recreating it?

**Comment by kpping** [comment]
I'm pushing programmatically with this code

``` objective-c
@interface A ()
{
    B bController;
}

- (void)navigateToB
{
    if(!bController)
        bController = [[B alloc] init];

    // push to B
}
```

It seems like when popping  bController, It doesn't deallocate.
